# Generated by Django 3.2 on 2021-10-23 19:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_title', models.CharField(max_length=200)),
                ('en_title', models.CharField(max_length=200)),
                ('fr_slug', models.SlugField(max_length=250, unique_for_date='pub_date')),
                ('en_slug', models.SlugField(max_length=250, unique_for_date='pub_date')),
                ('author', models.CharField(max_length=80)),
                ('fr_description', models.TextField(blank=True)),
                ('en_description', models.TextField(blank=True)),
                ('fr_content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('en_content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('post_img', models.ImageField(null=True, upload_to='media')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
