# Generated by Django 3.2 on 2021-07-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
