# Generated by Django 3.2 on 2021-07-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('showcase', '0002_showcase_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Showcase',
            new_name='Project',
        ),
    ]
